### ISSUE TITLE
只支持 SOCKS5 upstream proxy？支持 http upstream proxy 麽？

### ISSUE THREAD

**Issue by jzp820927** [XiaoxiaoPu/sniproxy#1]
只支持 SOCKS5 upstream proxy？支持 http upstream proxy 麽？

**Comment by puxxustc** [comment]
@jzp820927 不支持 HTTP proxy 。

**Comment by jzp820927** [comment]
再问个问题，能不能单独监听 443？不监听 80

**Comment by puxxustc** [comment]
@jzp820927 不能，自己把监听80端口的代码注释掉吧

**Comment by jzp820927** [comment]
好吧，我这边正在用的 upstream 是 http 的，请问下，能有什么工具可以转到 s5 的吗？
